(function() {var implementors = {};
implementors["libyubihsm"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libyubihsm/struct.yh_capabilities.html\" title=\"struct libyubihsm::yh_capabilities\">yh_capabilities</a>",synthetic:false,types:["libyubihsm::yubihsm_sys::yh_capabilities"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libyubihsm/struct.Domain.html\" title=\"struct libyubihsm::Domain\">Domain</a>",synthetic:false,types:["libyubihsm::types::Domain"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libyubihsm/enum.ReturnCode.html\" title=\"enum libyubihsm::ReturnCode\">ReturnCode</a>",synthetic:false,types:["libyubihsm::types::ReturnCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libyubihsm/enum.ObjectType.html\" title=\"enum libyubihsm::ObjectType\">ObjectType</a>",synthetic:false,types:["libyubihsm::types::ObjectType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libyubihsm/enum.Algorithm.html\" title=\"enum libyubihsm::Algorithm\">Algorithm</a>",synthetic:false,types:["libyubihsm::types::Algorithm"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libyubihsm/enum.Capability.html\" title=\"enum libyubihsm::Capability\">Capability</a>",synthetic:false,types:["libyubihsm::types::Capability"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libyubihsm/enum.Command.html\" title=\"enum libyubihsm::Command\">Command</a>",synthetic:false,types:["libyubihsm::types::Command"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"libyubihsm/enum.CommandType.html\" title=\"enum libyubihsm::CommandType\">CommandType</a>",synthetic:false,types:["libyubihsm::types::CommandType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"libyubihsm/struct.Yubihsm.html\" title=\"struct libyubihsm::Yubihsm\">Yubihsm</a>",synthetic:false,types:["libyubihsm::yubihsm::Yubihsm"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
